app <- ShinyDriver$new("../../")
app$snapshotInit("r-server")

app$setInputs(R_packages = "data.table")
app$setInputs(R_date_range_input = c("2015-12-27", "2022-07-07"))
app$setInputs(sidebar = TRUE)
app$setInputs(sidebar_menu = "python-downloads")
app$setInputs(sidebar = FALSE)
app$setInputs(run_query = "click")
app$setInputs(sidebar = TRUE)
app$setInputs(sidebar_menu = "R-downloads")
app$setInputs(sidebar = FALSE)
app$setInputs(customSwitch1 = FALSE)
app$setInputs(customSwitch1 = TRUE)
app$snapshot()
app$setInputs(sidebar = TRUE)
app$setInputs(sidebar_menu = "python-downloads")
app$setInputs(sidebar = FALSE)
app$snapshot()
